server.port=8082
spring.application.name=analytics-service

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=xauusd-analytics-group

# Use an Error Handler so bad messages don't break the app
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Ignore the class path tags sent by the ingestion service
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Treat the incoming message data directly as a plain Text String
spring.kafka.consumer.properties.spring.json.value.default.type=java.lang.String